# action.yml
name: 'zalexki php-cs-fixer'
branding:
  icon: 'award'  
  color: 'green'
description: 'php-cs-fixer for 7.3'
inputs:
  other-cmds:
    description: 'Add some configs'
    required: false
    default: '--dry-run --diff --using-cache=no --diff-format udiff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.other-cmds }}